"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MODULE_SOMETHING_WRONG = exports.MODULE_MISSING_ENTITY = exports.MODULE_INVALID_TYPE_ENTITY = exports.MODULE_INVALID_ENTITY = exports.MODULE_ERROR = void 0;
const MODULE_ERROR = () => `An error has occurred in @Module(), please check the detail field`;
exports.MODULE_ERROR = MODULE_ERROR;
const MODULE_INVALID_ENTITY = (entity) => `The content of the "${entity}" entity must be type "class".`;
exports.MODULE_INVALID_ENTITY = MODULE_INVALID_ENTITY;
const MODULE_INVALID_TYPE_ENTITY = (entity) => `There are ${entity} that do not match the allowed types "class" or "object with provider and use value".`;
exports.MODULE_INVALID_TYPE_ENTITY = MODULE_INVALID_TYPE_ENTITY;
const MODULE_MISSING_ENTITY = (entity) => `missing entity '${entity}' into the @Module() decorator.`;
exports.MODULE_MISSING_ENTITY = MODULE_MISSING_ENTITY;
const MODULE_SOMETHING_WRONG = (entity) => `something is wrong in the '${entity}' entity of @module`;
exports.MODULE_SOMETHING_WRONG = MODULE_SOMETHING_WRONG;
