"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PRIMITIVE_TYPES = exports.MODULE_EXPORTS = exports.MODULE_SERVICES = exports.MODULE_CONTROLLERS = exports.MODULE_IMPORTS = exports.IS_EXPORT = exports.IS_SERVICE = exports.IS_CONTROLLER = exports.IS_IMPORTS = exports.IS_MODULE = exports.HAS_INJECT = exports.DEPENDENCIES_INJECT = exports.DEPENDENCIES_PARAMETERS = exports.DEPENDENCIES_CLASS = exports.DEPENDENCIES_CONSTRUCTOR = void 0;
exports.DEPENDENCIES_CONSTRUCTOR = "design:paramtypes";
exports.DEPENDENCIES_CLASS = "__dependencies:class__";
exports.DEPENDENCIES_PARAMETERS = "__dependencies:paramater__";
exports.DEPENDENCIES_INJECT = "__dependencies:inject__";
exports.HAS_INJECT = "__has:inject__";
exports.IS_MODULE = "__is:module__";
exports.IS_IMPORTS = "__is:import__";
exports.IS_CONTROLLER = "__is:controller__";
exports.IS_SERVICE = "__is:service__";
exports.IS_EXPORT = "__is:export__";
exports.MODULE_IMPORTS = "module:imports";
exports.MODULE_CONTROLLERS = "module:controllers";
exports.MODULE_SERVICES = "module:services";
exports.MODULE_EXPORTS = "module:exports";
exports.PRIMITIVE_TYPES = ["number", "string", "object", "array", "boolean"];
